name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

env:
  REGISTRY: docker.io
  IMAGE_NAME: buymybills/incollab-fe

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Skip running on PR if it's only a draft
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Only push to Docker Hub on main branch, not on PRs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: buymybills
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Only push on main branch
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            buymybills/incollab-fe:latest
            buymybills/incollab-fe:${{ github.sha }}
          cache-from: type=registry,ref=buymybills/incollab-fe:buildcache
          cache-to: type=registry,ref=buymybills/incollab-fe:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    # Only deploy on push to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: First Time Setup
        if: env.FIRST_DEPLOY == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
              newgrp docker
            fi
            
            # Install Nginx if not installed
            if ! command -v nginx &> /dev/null; then
              echo "Installing Nginx..."
              sudo apt-get install -y nginx
            fi

      - name: Setup Nginx Configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create Nginx configuration
            echo 'server {
                listen 80;
                server_name collabkaroo.buymybills.in;
                
                location / {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }' | sudo tee /etc/nginx/sites-available/incollab-fe
            
            sudo ln -s /etc/nginx/sites-available/incollab-fe /etc/nginx/sites-enabled/ || true
            sudo rm /etc/nginx/sites-enabled/default || true
            sudo nginx -t && sudo systemctl restart nginx

      - name: Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove existing container
            docker stop incollab-fe || true
            docker rm incollab-fe || true
            
            # Pull and run new container
            docker pull buymybills/incollab-fe:latest
            docker run -d \
              --name incollab-fe \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e HOSTNAME="0.0.0.0" \
              buymybills/incollab-fe:latest

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check if container is running
            if ! docker ps | grep -q incollab-fe; then
              echo "Container is not running!"
              exit 1
            fi
            
            # Check container health
            if [ "$(docker inspect -f '{{.State.Status}}' incollab-fe)" != "running" ]; then
              echo "Container is not healthy!"
              exit 1
            fi
            
            echo "Deployment verified successfully!"
            # Pull the latest image
            sudo docker pull buymybills/incollab-fe:latest
            
            # Stop and remove existing container
            sudo docker stop incollab-fe || true
            sudo docker rm incollab-fe || true
            
            # Run new container
            sudo docker run -d \
              --name incollab-fe \
              --restart unless-stopped \
              -p 3000:3000 \
              buymybills/incollab-fe:latest
            
            # Cleanup old images
            sudo docker system prune -f