name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

env:
  REGISTRY: docker.io
  IMAGE_NAME: buymybills/incollab-fe

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Skip running on PR if it's only a draft
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Only push to Docker Hub on main branch, not on PRs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: buymybills
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Only push on main branch
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            buymybills/incollab-fe:latest
            buymybills/incollab-fe:${{ github.sha }}
          cache-from: type=registry,ref=buymybills/incollab-fe:buildcache
          cache-to: type=registry,ref=buymybills/incollab-fe:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    # Only deploy on push to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/incollab-fe
            ./scripts/server.sh deploy

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check if container is running
            if ! docker ps | grep -q incollab-fe; then
              echo "Container is not running!"
              exit 1
            fi
            
            # Check container health
            if [ "$(docker inspect -f '{{.State.Status}}' incollab-fe)" != "running" ]; then
              echo "Container is not healthy!"
              exit 1
            fi
            
            echo "Deployment verified successfully!"
            # Pull the latest image
            sudo docker pull buymybills/incollab-fe:latest
            
            # Stop and remove existing container
            sudo docker stop incollab-fe || true
            sudo docker rm incollab-fe || true
            
            # Run new container
            sudo docker run -d \
              --name incollab-fe \
              --restart unless-stopped \
              -p 3000:3000 \
              buymybills/incollab-fe:latest
            
            # Cleanup old images
            sudo docker system prune -f